# Generated by Django 3.2.5 on 2021-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=30)),
                ('modelDate', models.CharField(max_length=30)),
                ('modelDesc', models.CharField(max_length=30)),
            ],
        ),
    ]
